/*
** EPITECH PROJECT, 2018
** macro_files.h
** File description:
** macro_files.h
*/

#ifndef MACRO_FILES_H_
#define MACRO_FILES_H_

#define DOT1 "image/dot.png"
#define DOT2 "image/dot.png"
#define DOT3 "image/dot.png"
#define LOAD "image/loading.png"
#define MENU "image/menu.png"
#define CROSS "image/redcross.png"
#define LINE "image/underline.png"
#define PAUSE "image/pause.png"
#define STICK "image/stick.png"
#define TICK "image/tick.png"
#define START_BUTTON "image/start_button.png"
#define BACKGROUND "image/game.png"
#define LOADING_MUSIC "sound/loading_music.wav"
#define MENU_MUSIC "sound/music_menu.ogg"
#define GAME_MUSIC "sound/music_game.ogg"
#define MOUSE_PRESSED "sound/mouse_is_pressed.ogg"
#define CUSTOMER_SELECTION "image/customer_selection.png"
#define CUSTOMER_1 "image/customers/customer1.png"
#define CUSTOMER_2 "image/customers/customer2.png"
#define CUSTOMER_3 "image/customers/customer3.png"
#define CUSTOMER_4 "image/customers/customer4.png"
#define CUSTOMER_5 "image/customers/customer5.png"
#define CUSTOMER_6 "image/customers/customer6.png"
#define CUSTOMER_7 "image/customers/customer7.png"
#define CUSTOMER_8 "image/customers/customer8.png"
#define CUSTOMER_9 "image/customers/customer9.png"
#define CUSTOMER_10 "image/customers/customer10.png"
#define SPEECH_1 "image/game_speech_1.png"
#define SPEECH_2 "image/game_speech_2.png"
#define SPEECH_3 "image/game_speech_3.png"
#define SPEECH_4 "image/game_speech_4.png"
#define HIGHSCORE "image/highscore.png"
#define RECIPES "image/recipes.png"
#define RECIPE_1 "image/recipes/recipe_one.png"
#define RECIPE_2 "image/recipes/recipe_two.png"
#define RECIPE_3 "image/recipes/recipe_three.png"
#define RECIPE_4 "image/recipes/recipe_four.png"
#define RECIPE_5 "image/recipes/recipe_five.png"
#define RECIPE_6 "image/recipes/recipe_six.png"
#define RECIPE_7 "image/recipes/recipe_seven.png"
#define RECIPE_8 "image/recipes/recipe_eight.png"
#define RECIPE_9 "image/recipes/recipe_nine.png"
#define RECIPE_10 "image/recipes/recipe_ten.png"
#define SQUARE_RECIPE "image/yellow_square.png"
#define HOW_TO_PLAY "image/how_to_play.png"
#define RECIPES_INFO_1 "image/recipes/recipe_one.png"
#define RECIPES_INFO_2 "image/recipes/recipe_two.png"
#define RECIPES_INFO_3 "image/recipes/recipe_three.png"
#define RECIPES_INFO_4 "image/recipes/recipe_four.png"
#define RECIPES_INFO_5 "image/recipes/recipe_five.png"
#define RECIPES_INFO_6 "image/recipes/recipe_six.png"
#define RECIPES_INFO_7 "image/recipes/recipe_seven.png"
#define RECIPES_INFO_8 "image/recipes/recipe_eight.png"
#define RECIPES_INFO_9 "image/recipes/recipe_nine.png"
#define RECIPES_INFO_10 "image/recipes/recipe_ten.png"
#define GAME_BG "image/game.png"
#define CURSOR_NORMAL "image/cursor/cursor_empty.png"
#define CURSOR_CLICKED "image/cursor/cursor_full.png"
#define BEEF "image/ingredients/beef.png"
#define CHEESE "image/ingredients/cheese.png"
#define CREAM "image/ingredients/cream.png"
#define EGG "image/ingredients/egg.png"
#define FISH "image/ingredients/fish.png"
#define FLOUR "image/ingredients/flour.png"
#define NOODLES "image/ingredients/noodles.png"
#define RICE "image/ingredients/rice.png"
#define SAUSAGE "image/ingredients/sausage.png"
#define VEGGIES "image/ingredients/VEGGIES.png"
#define ARROW_FILE "image/yellow_arrow.png"
#define IN_GAME_GUIDE "image/game_guide.png"
#define GAME_HP "image/game_hp.png"
#define ASIAN_HOT_DOG "image/dishes/asian_hot_dog.png"
#define CHINESE_CANOLI "image/dishes/chinese_canoli.png"
#define CHINESE_FETA_SALAD "image/dishes/chinese_feta_salad.png"
#define INDIAN_PASTRY "image/dishes/indian_pastry.png"
#define JAPANESE_CALIFORNIA_SUSHI "image/dishes/japanese_california_sushi.png"
#define JAPANESE_SAWTEED_NOODLES "image/dishes/japanese_sawteed_noodles.png"
#define KOREAN_CHILI_CONE_CARNE "image/dishes/korean_chili_cone_carne.png"
#define KOREAN_KEBAB "image/dishes/korean_kebab.png"
#define VIETNAME_CREME_BRULEE "image/dishes/vietname_creme_brulee.png"
#define VIETNAMESE_BEEF_SUSHI "image/dishes/vietnamese_beef_sushi.png"
#define PREP_BOARD_PIC "image/question_mark.png"
#define BAD_DISH_PIC "image/bad_dish.png"
#define GOOD_BUBBLE_PIC "image/bubble_good.png"
#define BAD_BUBBLE_PIC "image/bubble_bad.png"
#define GAME_VICTORY "image/game_victory.png"
#define GAME_DEFEAT "image/game_defeat.png"
#define WINNING_MUSIC "sound/music_win.ogg"
#define LOSING_MUSIC "sound/music_lose.ogg"
#endif
